import Appbar from "@/component/Appbar";
import Drawer from "@/component/drawer";
const drawerWidth = 240;
export const metadata = {
  title: "Prisma App Mongodb",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Appbar drawerWidth={drawerWidth} />
        <Drawer />
        {children}
      </body>
    </html>
  );
}
