import Appbar from "@/component/Appbar";
import Drawer from "@/component/drawer";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
          <Appbar />
          <Drawer />
       
        {children}
        
      </body>
    </html>
  );
}
